"""
Download curated word lists from free public sources.
Builds the foundation word database by grade level.
Run: python scripts/01_download_wordlists.py
"""

import json
import time
import requests
import pandas as pd
from pathlib import Path

Path("backend/data/wordlists").mkdir(
    parents=True, exist_ok=True
)

HEADERS = {"User-Agent": "Educational Research Project"}

# ── GRADE-LEVEL CURATED WORD LISTS ────────────────────────────
# These are carefully curated by grade level
# Sources: Common Core, Scripps, educational research

GRADE_WORDS = {
    2: [
        "about", "after", "again", "almost", "always",
        "animal", "another", "answer", "around", "asked",
        "because", "before", "being", "better", "between",
        "bigger", "bring", "brother", "brought", "build",
        "carry", "change", "children", "clean", "close",
        "coming", "could", "country", "different", "does",
        "during", "early", "earth", "enough", "every",
        "example", "eyes", "face", "family", "father",
        "first", "follow", "found", "friend", "front",
        "funny", "getting", "going", "great", "green",
        "group", "grow", "happy", "heard", "heavy",
        "hello", "here", "high", "himself", "home",
        "horse", "house", "hundred", "important", "inside",
        "itself", "keep", "kind", "knew", "know",
        "large", "later", "learn", "leave", "letter",
        "light", "living", "longer", "looked", "made",
        "maybe", "money", "morning", "most", "mother",
        "mountain", "move", "music", "myself", "never",
        "night", "north", "nothing", "number", "often",
        "once", "order", "other", "outside", "over",
        "own", "paper", "people", "picture", "place",
        "plant", "point", "pretty", "probably", "problem",
        "question", "quick", "quite", "really", "right",
        "river", "room", "round", "same", "school",
        "second", "sentence", "should", "since", "small",
        "something", "sometimes", "soon", "sound", "south",
        "space", "special", "start", "still", "stood",
        "story", "street", "strong", "study", "such",
        "sure", "table", "talk", "teacher", "their",
        "there", "these", "thing", "think", "those",
        "three", "through", "together", "told", "took",
        "toward", "town", "trees", "tried", "true",
        "turned", "under", "until", "upon", "usually",
        "voice", "watch", "water", "ways", "weather",
        "where", "which", "white", "whole", "whose",
        "window", "without", "woman", "wonder", "words",
        "world", "would", "write", "wrong", "years",
        "young", "yourself",
    ],

    3: [
        "accept", "achieve", "action", "active", "address",
        "adventure", "against", "agree", "although", "among",
        "ancient", "appear", "April", "area", "argue",
        "arrive", "August", "author", "autumn", "available",
        "became", "believe", "beneath", "beyond", "bridge",
        "broken", "brother", "century", "certain", "character",
        "choose", "circle", "citizen", "clothing", "collect",
        "column", "comfort", "common", "complete", "contain",
        "continue", "corner", "correct", "costume", "cotton",
        "couple", "courage", "create", "creature", "culture",
        "danger", "daughter", "December", "decide", "declare",
        "decrease", "defeat", "describe", "design", "despite",
        "destroy", "develop", "direction", "discover", "distance",
        "divide", "doubt", "dragon", "dream", "either",
        "electric", "emotion", "empire", "empty", "energy",
        "engine", "enjoy", "entire", "equal", "escape",
        "evening", "event", "exact", "except", "exercise",
        "exist", "expect", "explain", "express", "extreme",
        "fabric", "famous", "feature", "February", "fierce",
        "figure", "finish", "forest", "forgot", "forward",
        "freedom", "future", "general", "gentle", "golden",
        "grateful", "gravel", "handle", "happen", "harbor",
        "harvest", "health", "heart", "height", "hidden",
        "history", "honor", "however", "hunger", "hunter",
        "include", "increase", "indeed", "island", "January",
        "journey", "jungle", "kingdom", "kitchen", "knight",
        "language", "launch", "leader", "leather", "lemon",
        "lesson", "library", "listen", "little", "lonely",
        "loose", "loudly", "lovely", "luckily", "magic",
        "manage", "manner", "marble", "market", "matter",
        "meadow", "meaning", "medicine", "middle", "mighty",
        "minute", "mirror", "modern", "moment", "monster",
        "museum", "mystery", "narrow", "nation", "nature",
        "nearby", "needle", "neither", "nervous", "notice",
        "November", "object", "ocean", "October", "offer",
        "office", "opened", "orange", "palace", "parent",
        "partner", "pattern", "perhaps", "period", "person",
        "phrase", "pilgrim", "plenty", "pocket", "poetry",
        "poison", "polite", "popular", "position", "possible",
        "power", "present", "prince", "princess", "private",
        "protect", "provide", "publish", "purple", "puzzle",
        "quarter", "quiet", "rather", "reason", "recent",
        "remain", "remind", "remove", "rescue", "result",
        "return", "review", "reward", "rhythm", "riddle",
        "rocket", "rough", "sadness", "safety", "salmon",
        "sample", "saving", "scared", "season", "secret",
        "several", "shadow", "shallow", "shape", "sharp",
        "shelter", "signal", "silver", "simple", "single",
        "sister", "sketch", "slowly", "smooth", "soldier",
        "someone", "source", "southern", "spoken", "spring",
        "square", "station", "statue", "steady", "summer",
        "sunset", "supply", "surface", "surprise", "symbol",
        "system", "target", "teamwork", "terrible", "thunder",
        "ticket", "timber", "tonight", "topic", "travel",
        "treasure", "trouble", "tunnel", "twelve", "twenty",
        "twice", "unique", "upper", "useful", "valley",
        "various", "village", "violent", "visitor", "voyage",
        "warrior", "waste", "western", "whether", "whisper",
        "winter", "wisdom", "within", "wonder", "wooden",
    ],

    4: [
        "abandon", "ability", "absence", "absorb", "abstract",
        "abundant", "accurate", "ache", "acknowledge", "acquire",
        "actual", "adapt", "addition", "adequate", "admire",
        "admission", "adopt", "advance", "advantage", "affect",
        "afford", "agriculture", "alliance", "allowance", "altitude",
        "ambassador", "ambition", "ancient", "announce", "anxiety",
        "appreciate", "appropriate", "approximately", "arctic", "argument",
        "arrangement", "assistance", "association", "atmosphere", "attach",
        "attempt", "attitude", "attract", "auction", "authority",
        "balance", "behavior", "benefit", "biography", "blossom",
        "boundary", "breathe", "brilliant", "bruise", "budget",
        "burglar", "calendar", "campaign", "capacity", "capital",
        "capture", "category", "celebrate", "challenge", "champion",
        "chaos", "charity", "chemical", "chorus", "circumference",
        "circumstance", "civilization", "classify", "coefficient", "collapse",
        "combination", "communicate", "community", "comparison", "compete",
        "composition", "concentrate", "conclusion", "condition", "confidence",
        "conflict", "consequence", "considerable", "constitution", "construct",
        "continent", "contrast", "contribute", "controversial", "convenient",
        "conversation", "convince", "cooperative", "coordinate", "corporation",
        "correspond", "criticism", "curious", "currency", "cylinder",
        "damage", "debate", "decisive", "decline", "decrease",
        "dedicate", "defense", "definitely", "democracy", "demonstrate",
        "deposit", "depression", "diameter", "disappear", "discipline",
        "document", "dominant", "dramatic", "durable", "dwarf",
        "earnest", "efficient", "elaborate", "encourage", "enormous",
        "environment", "epidemic", "establish", "evaluate", "evidence",
        "evolution", "examine", "exceptional", "exhibit", "experience",
        "experiment", "exploration", "extension", "extraordinary", "facilitate",
        "fascinate", "flexible", "foundation", "frequent", "genuine",
        "geography", "glacier", "glamorous", "glorious", "gradual",
        "guarantee", "guardian", "gymnasium", "hibernate", "horizon",
        "humidity", "hydrogen", "imaginary", "immediate", "immortal",
        "independence", "inevitable", "influence", "ingredient", "initiative",
        "innocent", "institution", "integrity", "intellectual", "intense",
        "interview", "invisible", "jealousy", "laboratory", "legislation",
        "literature", "luminous", "maintenance", "magnificent", "majority",
        "mechanical", "memorable", "migration", "minimum", "miserable",
        "moderate", "molecule", "monarchy", "movement", "mysterious",
        "national", "naturally", "necessary", "negotiate", "notorious",
        "occasion", "opponent", "opportunity", "organization", "original",
        "parliament", "particular", "peninsula", "permanent", "permission",
        "physical", "plentiful", "pollution", "population", "portable",
        "potential", "precious", "prejudice", "preparation", "presence",
        "preserve", "primary", "privilege", "procedure", "process",
        "progress", "proportion", "proposal", "publication", "pursuit",
        "qualify", "quantity", "radiation", "reasonable", "recognize",
        "recommend", "reduction", "reference", "reflect", "regulation",
        "relationship", "reliable", "remarkable", "repetition", "reputation",
        "research", "resistance", "revolution", "sacrifice", "satisfactory",
        "scientific", "secretary", "separate", "sequence", "significant",
        "situation", "solution", "spectrum", "splendid", "statistics",
        "strategy", "structure", "substance", "sufficient", "suggestion",
        "superior", "technology", "telescope", "temperature", "territory",
        "thorough", "throughout", "tolerance", "tradition", "transparent",
        "tremendous", "uniform", "universal", "unnecessary", "valuable",
        "variation", "vegetation", "venture", "version", "vibration",
        "volunteer", "vulnerable", "wilderness", "withdrawal", "wonderful",
    ],

    5: [
        "abolish", "accelerate", "accommodate", "accumulate", "accusation",
        "acknowledge", "acquisition", "adolescent", "adversity", "aesthetic",
        "aggressive", "agriculture", "allegiance", "alleviate", "alliteration",
        "ambiguous", "amplify", "analogy", "analyze", "anecdote",
        "anonymous", "antagonist", "anticipate", "apparent", "approximately",
        "archaeology", "aristocracy", "articulate", "aspire", "assassinate",
        "assumption", "astonish", "atrocity", "attribute", "authentic",
        "authorize", "autonomous", "bankruptcy", "benevolent", "biography",
        "bureaucracy", "calculation", "catastrophe", "ceremony", "characteristic",
        "chronological", "circumstantial", "collaborate", "commemorate", "commentary",
        "compassion", "competent", "compliment", "comprehend", "compromise",
        "conceive", "controversy", "conventional", "correlation", "corruption",
        "counteract", "credibility", "cultivate", "cumulative", "deceive",
        "deceptive", "declaration", "dedicate", "defend", "deficiency",
        "deliberate", "denounce", "depression", "descend", "determination",
        "devastate", "dilemma", "discontent", "discretion", "discrimination",
        "dominate", "elaborate", "eloquent", "emphasize", "empirical",
        "encounter", "endurance", "epidemic", "equivalent", "escalate",
        "essential", "evaluate", "evolution", "exaggerate", "exclude",
        "exhibition", "expedition", "extensive", "extraordinary", "facilitate",
        "familiarity", "formidable", "fortitude", "fundamental", "generate",
        "generosity", "gradual", "gratitude", "grotesque", "guarantee",
        "hierarchy", "humanitarian", "hypothesis", "identical", "ideology",
        "illustrious", "imagination", "impartial", "implication", "incompatible",
        "indifferent", "infer", "infrastructure", "innovation", "inspiration",
        "integrity", "interaction", "interpret", "investigate", "irony",
        "isolation", "jurisdiction", "justification", "legislation", "legitimate",
        "liberation", "limitation", "logical", "mandate", "manuscript",
        "massacre", "mechanism", "mediation", "metaphor", "methodology",
        "meticulous", "migration", "misconception", "narrative", "negotiate",
        "observation", "obstacle", "opposition", "optimism", "organization",
        "originality", "overcome", "oxidation", "paradox", "participation",
        "passionate", "perception", "persecution", "perspective", "persuasion",
        "phenomenon", "philosophical", "prediction", "prejudice", "preservation",
        "protagonist", "provoke", "psychological", "publication", "rationalize",
        "rebellion", "recognition", "reformation", "rehabilitation", "reinforce",
        "reluctant", "representation", "resilience", "retaliation", "revelation",
        "revolutionary", "rigorous", "satire", "scandalous", "significant",
        "simultaneous", "skeptical", "sophistication", "speculation", "spontaneous",
        "subordinate", "substantial", "succession", "sympathize", "systematic",
        "transformation", "transition", "ultimate", "unanimous", "unprecedented",
        "utilization", "validity", "verification", "vigilance", "visualization",
    ],

    6: [
        "aberration", "abysmal", "acrimonious", "adamant", "admonish",
        "adulterate", "affluent", "aggravate", "aggrieve", "altruistic",
        "ameliorate", "anachronism", "anomaly", "antagonize", "apathetic",
        "apprehensive", "arduous", "audacious", "auspicious", "autocratic",
        "bellicose", "benign", "blatant", "brevity", "candid",
        "capricious", "catalyst", "caustic", "charismatic", "chronic",
        "clandestine", "coherent", "complacent", "comprehensive", "concise",
        "condescending", "conscience", "conscientious", "consistent", "conspicuous",
        "contempt", "contentious", "contrition", "conviction", "copious",
        "credulous", "cryptic", "debilitate", "decimate", "deference",
        "defiant", "degenerate", "denigrate", "denounce", "deprivation",
        "desolate", "despotism", "deteriorate", "devastation", "devout",
        "diligent", "discernment", "dismantle", "disparity", "dissent",
        "distraught", "diverge", "divisive", "dogmatic", "earnest",
        "eccentric", "egregious", "elusive", "empower", "enigmatic",
        "equivocal", "erroneous", "exacerbate", "exemplary", "exhaustive",
        "exonerate", "expedient", "explicit", "exuberant", "fallacious",
        "ferocious", "fervent", "flagrant", "flourish", "fluctuate",
        "formulate", "forthright", "fraudulent", "frivolous", "frugal",
        "futile", "galvanize", "grandiose", "gregarious", "hamper",
        "haphazard", "harrowing", "heinous", "heretical", "hypocritical",
        "idealistic", "illuminate", "illusory", "imminent", "implicit",
        "inadvertent", "incite", "inconsistent", "indignant", "indispensable",
        "inefficient", "insolent", "insurgent", "intermittent", "intricate",
        "irrelevant", "judgmental", "justifiable", "lament", "languish",
        "lenient", "lethargic", "lucid", "malicious", "malignant",
        "meager", "mediocre", "melancholy", "meticulous", "militant",
        "minimize", "mitigate", "moderate", "momentous", "monotonous",
        "morale", "mundane", "nefarious", "negligent", "nostalgic",
        "notorious", "nuance", "oblivious", "obsolete", "ominous",
        "oppressive", "ostracize", "outspoken", "pacifist", "painstaking",
        "partisan", "patronizing", "pervasive", "pessimistic", "petulant",
        "placate", "plausible", "pragmatic", "precarious", "precocious",
        "predominant", "preposterous", "presumptuous", "pretentious", "prodigious",
        "profound", "prolong", "propaganda", "proportional", "prosperous",
        "provocative", "prudent", "radical", "rampant", "raucous",
        "reciprocate", "reckless", "rectify", "redemption", "redundant",
        "refute", "relentless", "remorse", "renounce", "reprehensible",
        "repudiate", "resolute", "reticent", "ruthless", "sanctimonious",
        "scrutinize", "serene", "shrewd", "skeptical", "solemn",
        "somber", "sporadic", "steadfast", "stringent", "subjugate",
        "subtle", "superficial", "suppress", "turbulent", "ubiquitous",
        "undermine", "unequivocal", "usurp", "vehement", "venerate",
        "verbose", "vicious", "volatile", "zealous", "zealotry",
    ],

    7: [
        "abhorrent", "abstruse", "accolade", "acrimony", "acumen",
        "adulation", "aegis", "affable", "aggrandize", "alacrity",
        "ambivalence", "ameliorate", "amicable", "anachronistic", "anarchy",
        "animosity", "appease", "arbitrary", "archaic", "ardor",
        "ascertain", "aspersion", "assiduous", "atone", "audacity",
        "austere", "avarice", "axiom", "beguile", "belligerent",
        "benefactor", "benevolent", "bombastic", "bravado", "brevity",
        "burgeon", "cacophony", "callous", "capitulate", "castigate",
        "censure", "chicanery", "circumspect", "clemency", "coerce",
        "cogent", "compunction", "conciliatory", "condone", "confiscate",
        "convoluted", "corroborate", "counterintuitive", "culpable", "dauntless",
        "debunk", "decrepit", "defamation", "deference", "deferential",
        "demagogue", "demise", "derision", "desolation", "despondent",
        "diatribe", "dilapidated", "dilettante", "dirge", "discordant",
        "disdain", "disparage", "dissolution", "dogma", "dormant",
        "duplicity", "ebullient", "edify", "efface", "effrontery",
        "egregious", "elicit", "embroil", "eminence", "empiricism",
        "endemic", "ephemeral", "equanimity", "equivocate", "eradicate",
        "estranged", "euphemism", "exasperate", "excerpt", "excoriate",
        "execrate", "exonerate", "expeditious", "expunge", "extemporaneous",
        "extravagant", "exultant", "fabricate", "fathom", "fervid",
        "filibuster", "flippant", "foment", "forbearance", "forestall",
        "forsake", "fractious", "fraudulence", "frugality", "furtive",
        "garrulous", "glacial", "gluttony", "gratuitous", "guile",
        "hallowed", "harbinger", "harrowing", "hubris", "hyperbole",
        "iconoclast", "ideology", "idiosyncrasy", "ignoble", "illuminate",
        "immutable", "impeccable", "imperious", "implacable", "imprudent",
        "impudent", "incendiary", "incompetence", "incredulous", "indignation",
        "indolent", "inexorable", "ingenious", "inimical", "innocuous",
        "insinuate", "instigate", "integrity", "intransigent", "invective",
        "irascible", "irreverent", "laconic", "lampoon", "languid",
        "lassitude", "levity", "loquacious", "lugubrious", "magnanimous",
        "malfeasance", "malignant", "manifest", "maverick", "mendacious",
        "mercurial", "methodical", "misanthrope", "mitigate", "mollify",
        "moratorium", "mortify", "myopic", "nebulous", "nefarious",
        "nihilism", "nominal", "notorious", "noxious", "obdurate",
        "obsequious", "obstinate", "obtuse", "officious", "ominous",
        "ostentatious", "ostracism", "overture", "palliative", "paradoxical",
        "pariah", "parsimonious", "partisan", "pathological", "pedantic",
        "pernicious", "pertinacious", "petulance", "philanthropy", "placid",
        "plausible", "plethora", "polemical", "pompous", "pontificate",
        "pragmatism", "preclude", "predilection", "prerogative", "prevaricate",
        "probity", "profligate", "profuse", "prolific", "propagate",
        "propitiate", "proscribe", "protract", "provenance", "provincial",
        "prudent", "purport", "querulous", "rancorous", "rapacious",
        "raze", "recant", "reclusive", "rectitude", "redress",
        "refute", "renounce", "replete", "reprobate", "rescind",
        "resignation", "reticent", "ruminate", "sagacious", "sanction",
        "sanguine", "sardonic", "scandalous", "scrupulous", "secession",
        "squalid", "squander", "stagnant", "stoic", "stratagem",
        "strident", "subversive", "supercilious", "surreptitious", "tangential",
        "tenacious", "terse", "timorous", "toil", "torpor",
        "tractable", "transgress", "treacherous", "trepidation", "trivial",
        "truncate", "tumultuous", "turmoil", "tyrannical", "usurpation",
        "vacuous", "validate", "vanquish", "venomous", "verbose",
        "vicarious", "vindicate", "virulent", "vitriolic", "vociferous",
        "wanton", "wary", "zealous",
    ],
}

# SAT level words for grades 8-10
SAT_WORDS = {
    8: [
        "abate", "abdicate", "aberrant", "abjure", "abscond",
        "abstemious", "abstruse", "accrete", "acerbic", "acquiesce",
        "acrimony", "adumbrate", "adverse", "advocate", "affinity",
        "aggrandize", "agitate", "alacrity", "altruism", "amalgam",
        "ambiguous", "ameliorate", "amorphous", "anachronism", "analogous",
        "anomalous", "antagonistic", "apathetic", "approbation", "aptitude",
        "archaic", "arduous", "arid", "articulate", "ascetic",
        "astute", "atrophy", "attenuate", "augment", "austere",
        "autocrat", "avarice", "aversion", "bane", "bedlam",
        "belie", "belligerent", "bemoan", "beneficent", "benign",
        "besmirch", "bizarre", "blatant", "bolster", "bombast",
        "boon", "brazen", "brevity", "brusque", "bucolic",
        "burgeon", "cacophony", "callous", "capricious", "catalyst",
        "caustic", "censure", "chagrin", "chicanery", "chronological",
        "circuitous", "clemency", "coalesce", "cogent", "cohere",
        "compunction", "concise", "concur", "condescend", "confound",
        "convoluted", "copious", "cordial", "corroborate", "credulous",
        "culpable", "cursory", "cynical", "dauntless", "dearth",
        "decry", "deference", "deft", "demure", "denounce",
        "derision", "desiccate", "desolate", "desultory", "diatribe",
        "diffident", "digress", "dilettante", "dirge", "dissonance",
        "dogmatic", "dubious", "duplicity", "ebullient", "efface",
        "elaborate", "eloquent", "emulate", "endemic", "enigmatic",
        "equanimity", "equivocate", "erratic", "erudite", "esoteric",
        "ethereal", "evocative", "exacerbate", "exculpate", "exert",
        "exhaustive", "expedient", "expunge", "exuberant", "fallacious",
        "fastidious", "fatuous", "fervent", "flagrant", "florid",
        "foment", "forbearance", "forthright", "frugal", "furtive",
        "garrulous", "grandiloquent", "gratuitous", "guile", "harbinger",
        "hegemony", "heresy", "hubris", "hypocritical", "iconoclast",
        "idiosyncrasy", "ignoble", "immutable", "imperious", "implacable",
        "impudent", "incendiary", "incredulous", "indolent", "inexorable",
        "ingenious", "innocuous", "insidious", "instigate", "intransigent",
        "irascible", "laconic", "languid", "lassitude", "loquacious",
        "magnanimous", "mendacious", "mercurial", "misanthrope", "mollify",
        "morose", "myopic", "nefarious", "nihilism", "obdurate",
        "obsequious", "obstinate", "officious", "ostentatious", "ostracism",
        "parsimonious", "pedantic", "pernicious", "philanthropic", "placid",
        "plethora", "polemical", "pompous", "pragmatic", "preclude",
        "prerogative", "prevaricate", "probity", "profligate", "prolific",
        "propitiate", "provincial", "purport", "querulous", "rancorous",
        "rapacious", "recant", "rectitude", "refute", "renounce",
        "reprobate", "rescind", "reticent", "ruminate", "sagacious",
        "sanguine", "sardonic", "scrupulous", "stoic", "stratagem",
        "strident", "subversive", "supercilious", "surreptitious", "tenacious",
        "timorous", "torpor", "tractable", "transgress", "trepidation",
        "truncate", "turmoil", "tyrannical", "usurpation", "vacuous",
        "venomous", "verbose", "vicarious", "vitriolic", "vociferous",
    ],
    9: [
        "abrogate", "absolution", "acerbic", "acumen", "adroit",
        "adversarial", "aesthetic", "affectation", "aggrandizement", "aghast",
        "alacrity", "amalgamate", "ambivalent", "ameliorate", "amorphous",
        "anachronistic", "anathema", "antithetical", "apocryphal", "appease",
        "apotheosis", "arbitrary", "arcane", "ardent", "ascertain",
        "assiduous", "atone", "audacious", "augment", "austerity",
        "avarice", "axiom", "banal", "beguile", "bellicose",
        "bemused", "benefactor", "benevolent", "bombastic", "brevity",
        "burgeon", "cacophony", "callous", "capitulate", "castigate",
        "cathartic", "censure", "circumspect", "clandestine", "cogent",
        "collusion", "compunction", "confiscate", "convoluted", "corroborate",
        "culpable", "dauntless", "debilitate", "demagogue", "derision",
        "despot", "dilapidated", "dilettante", "discordant", "disdain",
        "disparage", "dissolution", "dogma", "duplicity", "ebullient",
        "edify", "efface", "elicit", "embroil", "empiricism",
        "endemic", "ephemeral", "equanimity", "equivocate", "eradicate",
        "esoteric", "euphemism", "excoriate", "exonerate", "expeditious",
        "extemporaneous", "fabricate", "fallacious", "fatuous", "fervid",
        "filibuster", "foment", "forestall", "fractious", "fraudulence",
        "furtive", "garrulous", "gluttony", "grandiose", "gratuitous",
        "guile", "harbinger", "hegemony", "hubris", "hyperbole",
        "iconoclast", "idiosyncrasy", "ignoble", "illuminate", "immutable",
        "impeccable", "imperious", "implacable", "impudent", "incendiary",
        "incredulous", "indolent", "inexorable", "instigate", "intransigent",
        "invective", "irascible", "laconic", "languid", "lassitude",
        "levity", "loquacious", "lugubrious", "magnanimous", "malfeasance",
        "malignant", "maverick", "mendacious", "mercurial", "misanthrope",
        "mollify", "moratorium", "mortify", "myopic", "nebulous",
        "nefarious", "nihilism", "notorious", "obdurate", "obsequious",
        "obtuse", "officious", "ominous", "ostentatious", "ostracism",
        "palliative", "pariah", "parsimonious", "pedantic", "pernicious",
        "pertinacious", "philanthropy", "placid", "plethora", "polemical",
        "pompous", "pontificate", "pragmatic", "preclude", "predilection",
        "prerogative", "prevaricate", "probity", "profligate", "prolific",
        "propagate", "propitiate", "proscribe", "protract", "provincial",
        "purport", "querulous", "rancorous", "rapacious", "recant",
        "rectitude", "redress", "refute", "renounce", "replete",
        "reprobate", "rescind", "reticent", "ruminate", "sagacious",
        "sanction", "sanguine", "sardonic", "scrupulous", "secession",
        "squalid", "squander", "stoic", "stratagem", "strident",
        "subversive", "supercilious", "surreptitious", "tangential", "tenacious",
        "terse", "timorous", "torpor", "tractable", "transgress",
        "treacherous", "trepidation", "truncate", "tumultuous", "tyrannical",
        "usurpation", "vacuous", "venomous", "verbose", "vicarious",
        "vitriolic", "vociferous", "wanton", "zealous",
    ],
    10: [
        "abeyance", "abnegation", "abrogate", "abstemious", "accolade",
        "accretion", "acrimony", "acuity", "adumbrate", "aesthete",
        "affectation", "aggrandizement", "alacrity", "amalgam", "ameliorate",
        "amortize", "anachronism", "anathema", "antithesis", "apocryphal",
        "apotheosis", "approbation", "archaic", "ardor", "asceticism",
        "assiduous", "atrophy", "attenuate", "audacity", "austerity",
        "avarice", "axiom", "banal", "beguile", "bellicose",
        "bemuse", "beneficent", "benevolent", "bombast", "boon",
        "brazen", "brevity", "brusque", "bucolic", "burgeon",
        "cacophony", "callous", "capricious", "catalyst", "caustic",
        "censure", "chagrin", "chicanery", "circuitous", "clemency",
        "coalesce", "cogent", "compunction", "concur", "condescend",
        "confound", "convoluted", "copious", "corroborate", "credulous",
        "culpable", "cursory", "cynical", "dauntless", "dearth",
        "decry", "deference", "deft", "demure", "denounce",
        "derision", "desolate", "desultory", "diatribe", "diffident",
        "digress", "dilettante", "dirge", "dissonance", "dogmatic",
        "dubious", "duplicity", "ebullient", "efface", "eloquent",
        "emulate", "endemic", "enigmatic", "equanimity", "equivocate",
        "erratic", "erudite", "esoteric", "ethereal", "evocative",
        "exacerbate", "exculpate", "expedient", "expunge", "exuberant",
        "fallacious", "fastidious", "fatuous", "fervent", "flagrant",
        "florid", "foment", "forbearance", "frugal", "furtive",
        "garrulous", "grandiloquent", "gratuitous", "guile", "harbinger",
        "hegemony", "heresy", "hubris", "iconoclast", "idiosyncrasy",
        "ignoble", "immutable", "imperious", "implacable", "impudent",
        "incendiary", "incredulous", "indolent", "inexorable", "ingenious",
        "innocuous", "insidious", "instigate", "intransigent", "invective",
        "irascible", "laconic", "languid", "lassitude", "loquacious",
        "magnanimous", "mendacious", "mercurial", "misanthrope", "mollify",
        "morose", "myopic", "nefarious", "nihilism", "obdurate",
        "obsequious", "obstinate", "officious", "ostentatious", "ostracism",
        "parsimonious", "pedantic", "pernicious", "philanthropic", "placid",
        "plethora", "polemical", "pompous", "pragmatic", "preclude",
        "prerogative", "prevaricate", "probity", "profligate", "prolific",
        "propitiate", "provincial", "purport", "querulous", "rancorous",
        "rapacious", "recant", "rectitude", "refute", "renounce",
        "reprobate", "rescind", "reticent", "ruminate", "sagacious",
        "sanguine", "sardonic", "scrupulous", "stoic", "stratagem",
        "strident", "subversive", "supercilious", "surreptitious", "tenacious",
        "timorous", "torpor", "tractable", "transgress", "trepidation",
        "truncate", "turmoil", "tyrannical", "usurpation", "vacuous",
        "venomous", "verbose", "vicarious", "vitriolic", "vociferous",
    ],
}


def save_wordlists():
    """Save all word lists as JSON files."""
    all_words = {**GRADE_WORDS, **SAT_WORDS}

    total = 0
    for grade, words in sorted(all_words.items()):
        path = (f"backend/data/wordlists/"
                f"grade_{grade}_words.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump({
                "grade":      grade,
                "word_count": len(words),
                "words":      words
            }, f, indent=2)
        print(f"  Grade {grade}: {len(words)} words → {path}")
        total += len(words)

    print(f"\n✅ Total words saved: {total:,}")
    print(f"Next: python scripts/02_enrich_words.py")


if __name__ == "__main__":
    print("="*55)
    print("SPELLING BEE WORD LIST BUILDER")
    print("="*55)
    print()
    save_wordlists()